### ISSUE TITLE
Load this library using Packagist

### ISSUE THREAD

**Issue by fastslack** [phproberto/joomla-entity#25]
Hola Roberto!

I want to know if will be possible in the future to use this library using composer/packagist for standalone applications.

Regards

**Comment by phproberto** [comment]
Hola Matías!

I didn't publish it because it would cause extensions to ship it and cause issues with duplicated loading. But it makes total sense for standalone applications or even for testing purposes.

I will publish it today. Thanks for your feedback!

**Comment by phproberto** [comment]
In fact is already published and used by the package:

https://packagist.org/packages/phproberto/joomla-entity

You can install it with:

`composer require phproberto/joomla-entity`

The package is just a wrapper over the packagist library:

https://github.com/phproberto/joomla-entity-pkg/blob/master/extensions/libraries/joomla_entity/composer.json#L16

**Comment by fastslack** [comment]
thanks!!
