### ISSUE TITLE
create method

### ISSUE THREAD

**Issue by anibalsanchez** [phproberto/joomla-entity#4]
Amazing stuff!!

I understand that the method to create instances is **instance**... and that's mainly because of Joomla's current practice.

To depart from the old practice, I'd love to have the verb to the action of object creation as **create**... it could be simply an alias.

Again, thank you @phproberto !

**Comment by phproberto** [comment]
Thanks for the feedback. I really appreciate you took the time to review it.

I agree the name is developer oriented and bad semantically. Rolando suggested to use `find` at JoomlaDay Vigo and I think is a good choice. I will change it. 

Thanks again.

**Comment by phproberto** [comment]
I've sent a PR: https://github.com/phproberto/joomla-entity/pull/6

Let me know your thoughts about it. 

Let's close this and discuss it there. 

Thanks again for the feedback!

**Comment by anibalsanchez** [comment]
Cool
